### PR TITLE
Add more features

### PR DESCRIPTION
**Pull request by amanagr**

### CODE REVIEW

**Comment by amanagr** [comment]
@rr- let me know if there are any problems or anything u would like to be changed. OR if u are busy, u can say so. I will wait.

**Comment by rr-** [comment]
I'm busy with other stuff, I have the ticket in my mailbox queue :)

**Comment by rr-** [comment]
@amanagr can I commit to your branch?

**Comment by amanagr** [comment]
sure

**Comment by rr-** [comment]
Added my two cents, LMK what you think

**Comment by amanagr** [comment]
LGTM. Thanks @rr- !

**Comment by amanagr** [comment]
@rr- I am waiting on a release for this. Could you do one?

**Comment by rr-** [comment]
Done

**Pull request merged**
